openapi: 3.0.0
info:
  title: Чат-бот проведения мероприятий
  description: |-
    Телеграм-бот, для создания мероприятий, бронирования для них разных объектов (переговорки, оборудование), приглашения участников на мероприятия и чекина на мероприятих.
  version: 1.0.0
paths:
  /user/login:
    get:
      tags:
        - user
      summary: Вход пользователя в систему
      operationId: login
      parameters:
        - name: username
          in: query
          required: false
          schema:
            type: string
        - name: password
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Успешно
        '400':
          description: Неправильный логин или пароль
  /user/logout:
    get:
      tags:
        - user
      summary: Выход из системы
      description: ''
      operationId: logout
      parameters: []
      responses:
        default:
          description: Успешно
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: jonh
        password:
          type: string
          example: '12345'
